### ISSUE TITLE
Landlock availability check

### ISSUE THREAD

**Issue by l0kod** [quitesimpleorg/qssb.h#1]
`exile_landlock_is_available()` doesn't correctly check Landlock availability:
https://github.com/quitesimpleorg/exile.h/blob/8f38dc4480d51e2bf737ef87dd4a4f408d90a8a6/exile.c#L363-L364

Indeed, this `landlock_create_ruleset()` call returns the Landlock ABI version which should be greater than 0, not only equal to 1.

**Comment by crtxcr** [comment]
Hi Mickaël,

nice to see you here, Landlock is great work! Thanks for reporting this, I've pushed the fix to the next branch

**Comment by l0kod** [comment]
Thanks. Nice work!
